# Generated by Django 3.2.8 on 2021-11-08 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_posts_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 22, 4, 35, 836307, tzinfo=utc)),
        ),
    ]
