# Generated by Django 3.2.8 on 2021-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_posts_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_photo',
            field=models.ImageField(default='./media/network/img/black_background.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='./media/network/img/default_user_photo.jpg', upload_to=''),
        ),
    ]
