# Generated by Django 3.2.8 on 2021-11-14 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
